apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ntmdu3fk6-go 
  janus-idp.io/tekton: ntmdu3fk6-go
  backstage.io/kubernetes-id: ntmdu3fk6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntmdu3fk6-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml